apiVersion: apps/v1
kind: Deployment
metadata: 
  name: my-deploy
  labels: 
    app: demo-app
spec: 
  template: 
    metadata:
      labels:
        app: demo-app
    spec: 
      containers:
        - name: my-container
          image: httpd:latest
          ports:
            - containerPort: 80
  replicas: 3
  selector: 
    matchExpressions:
      - {key: app, operator: In, values: [demo-app] }
  strategy:
    type: RollingUpdate
---

apiVersion: v1
kind: Service
metadata:
  name: my-deploy-service
  labels:
    app: demo-app
spec:
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      name: http
  selector:
    app: demo-app
  type: NodePort