apiVersion: v1
kind: Pod
metadata: 
  name: my-pod
  labels:
    app: cloth-app
spec: 
  containers: 
  - name: nginx-app
    image: nginx
    ports:
      - containerPort: 80
    resources:
      requests:
        cpu: 100m
        memory: 200M
      limits: 
        cpu: 200m
        memory: 400M