apiVersion: v1
kind: ReplicationController
metadata: 
  name: my-rc
  labels: 
    app: my-app
spec: 
  template: 
    metadata:
      labels:
        app: my-app
    spec: 
      containers:
        - name: my-conatainer
          image: nginx:latest
          ports:
            -conatainerPort: 80
  replicas: 3
  selector: 
    app: my-app