apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-app
spec:
  ports:
    - targetPort: 80
      port: 80
      protocol: TCP
      name: http
  selector:
    app: my-app
  type: NodePort